---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: odk-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enketo
            port:
              number: 8005